insert into questoes_respostas values
	(default, 'Normalmente, quantos litros de sangue uma pessoa tem?', 'Tem entre 4 a 6 litros', 'Tem entre 2 a 4 litros', 'Tem 10 litros', 'Tem 7 litros', 3, 'i'),
	(default, 'Em qual local da Ásia o português é língua oficial?', 'Macau', 'Moçambique', 'Filipinas', 'Índia', 3, 'v'),
    (default, 'O etanol é produzido através de qual fonte de energia?', 'Biomassa', 'Eólica', 'Solar', 'Geotérmica', 3, 'v'),
    (default, 'Que povo foi o primeiro a utilizar a bússola?', 'chineses', 'romanos', 'mesopotâmicos', 'egípcios', 3, 'v'),
    (default, 'Em que estado australiano fica situada a cidade de Sydney?', 'Nova Gales do Sul', 'Victoria', 'Tasmânia', 'Norfolk', 3, 'v'),
    (default, 'Quantos ossos temos no nosso corpo?', '206', '126', '300', '200', 3, 'v'),
    (default, 'Quantos andares tem o maior prédio do mundo?', '163', '100', '200', '25', 3, 'i'),
    (default, 'Qual é o maior arquipélago da Terra?', 'a Indonésia', 'as Filipinas', 'as Bahamas', 'as Maldivas', 3, 'v'),
    (default, 'Em que oceano fica Madagascar?', 'Índico', 'Antártico', 'Atlântico', 'Pacífico', 3, 'v'),
    (default, 'Quem viveu, segundo a bíblia, 969 anos?', 'Matusalém', 'Jesus Cristo', 'Noé', 'Abel', 3, 'v'),
    (default, 'Quem foi o criador da tragédia grega?', 'Ésquilo', 'Homero', 'Sófocles', 'Platão', 3, 'v'),
    (default, 'Jim Morrison era vocalista de que grupo?', 'The Doors', 'The Police', 'Nirvana', 'Pink Floyd', 3, 'v'),
    (default, 'Quem foi a primeira pessoa a viajar no Espaço?', 'Yuri Gagarin', 'Marcos Pontes', 'Buzz Aldrin', 'Neil Armstrong', 3, 'v'),
    (default, 'Qual a nacionalidade do sociólogo e filósofo Durkheim?', 'Francesa', 'Inglesa', 'Italiana', 'Norueguesa', 3, 'v'),
    (default, 'Quantos continentes existem?', '6', '5', '4', '7', 3, 'v'),
    (default, 'Quanto mede uma girafa?', 'Entre 4,8 e 5,5 metros', '2 metros', '2,5 metros', 'Entre 5 e 6 metros', 3, 'v'),
    (default, 'Como se chama o passarinho amarelo amigo de Snoopy?', 'Woodstock', 'Magoo', 'Wile', 'Bobby', 3, 'v'),
    (default, '“It is six twenty" ou "twenty past six”. Que horas são em inglês?', '6:20', '2:20', '12:06', '6:02', 3, 'v'),
    (default, 'Júpiter e Plutão são os correlatos romanos de quais deuses gregos?', 'Zeus e Hades', 'Cronos e Apolo', 'Zeus e Ares', 'Ares e Hermes', 3, 'v'),
    (default, 'Em que período da pré-história o fogo foi descoberto?', 'Paleolítico', 'Neolítico', 'Idade dos Metais', 'Período da Pedra Polida', 3, 'v'),
    (default, 'De quem é a famosa frase “Penso, logo existo”?', 'Descartes', 'Platão', 'Galileu Galilei', 'Sócrates', 2, 'v'),
    (default, 'Que líder mundial ficou conhecida como “Dama de Ferro”?', 'Margaret Thatcher', 'Angela Merkel', 'Hillary Clinton', 'Dilma Rousseff', 2, 'v'),
	(default, 'Quem pintou "Guernica"?', 'Pablo Picasso', 'Paul Cézanne', 'Diego Rivera', 'Tarsila do Amaral', 2, 'i'),
    (default, 'Quantos braços tem um polvo?', 'Oito', 'Seis', 'Sete', 'Dez', 2, 'i'),
    (default, 'Nesses pares, ambos são mamíferos:', 'Baleia azul e golfinhos', 'Macacos e sapos', 'Porcos e pinguins', 'Morcegos e galinhas', 2, 'v'),
    (default, 'Quanto tempo o vidro demora para se decompor?', 'tempo indeterminado', '4000 anos', '1000 anos', '500 anos', 2, 'v'),
    (default, 'De que são constituídos os diamantes?', 'Carbono', 'Rênio', 'Bóhrio', 'Ósmio', 2, 'v'),
    (default, 'Quanto tempo a luz do Sol demora para chegar à Terra?', '8 minutos', '12 minutos', '1 dia', '12 horas', 2, 'v'),
    (default, 'Quem pintou o teto da capela sistina?', 'Michelangelo', 'Rafael', 'Leonardo da Vinci', 'Donatello', 2, 'v'),
    (default, 'Qual a primeira mulher a ganhar um prêmio Nobel?', 'Marie Curie', 'Valentina Tereshkova', 'Madre Teresa de Calcutá', 'Irène Joliot-Curie', 2, 'v'),
    (default, 'Como morreu Saddam Hussein?', 'Enforcado', 'Ataque cardíaco', 'Decapitado', 'Suicídio', 2, 'v'),
    (default, 'Qual a doença sexualmente transmissível que virou surto no Brasil em 2017?', 'Sífilis', 'Zika', 'Candidíase', 'Febre amarela', 2, 'v'),
    (default, 'Em que país se localizava Auschwitz, o maior campo de concentração nazi?', 'Polônia', 'Alemanha', 'Áustria', 'Japão', 2, 'v'),
    (default, 'Quantos planetas Terra cabem dentro do Sol?', 'Um milhão', 'Cem', 'Seiscentas', 'Dois milhões', 2, 'v'),
    (default, 'Quantos graus são necessários para que dois ângulos sejam complementares?', '90', '45', '360', '180', 2, 'v'),
    (default, 'Qual a nacionalidade de Che Guevara?', 'Argentina', 'Peruana', 'Panamenha', 'Boliviana', 2, 'v'),
    (default, 'Qual a altura da rede de vôlei nos jogos masculino e feminino?', '2,43 m e 2,24 m', '2,5 m e 2,0 m', '1,8 m e 1,5 m', '2,45 m e 2,15 m', 2, 'v'),
    (default, 'De onde é a invenção do chuveiro elétrico?', 'Brasil', 'França', 'Inglaterra', 'Austrália', 2, 'v'),
    (default, 'Quais o menor e o maior país do mundo?', 'Vaticano e Rússia', 'Nauru e China', 'Mônaco e Canadá', 'Malta e Estados Unidos', 2, 'v'),
    (default, 'Em que país nasceu o Conde Drácula?', 'Transilvânia', 'Irlanda', 'Escócia', 'Polônia', 2, 'i'),
    (default, 'Que país foi dividido em 1949?', 'Alemanha', 'Bélgica', 'Polônia', 'Dinamarca', 2, 'v'),
    (default, 'Qual o nome do presidente do Brasil que ficou conhecido como Jango?', 'João Goulart', 'Jacinto Anjos', 'Getúlio Vargas', 'João Figueiredo', 2, 'v'),
    (default, 'Qual o livro mais vendido no mundo a seguir à Bíblia?', 'Dom Quixote', 'O Senhor dos Anéis', 'O Pequeno Príncipe', 'Ela, a Feiticeira', 2, 'v'),
    (default, 'Quantas casas decimais tem o número pi?', 'Infinitas', 'Duas', 'Centenas', 'Vinte', 2, 'i'),
    (default, 'Atualmente, quantos elementos químicos a tabela periódica possui?', '118', '113', '109', '108', 2, 'v'),
    (default, 'Quem inventou a lâmpada?', 'Thomas Edison', 'Henry Ford', 'Santos Dumont', 'Steve Jobs', 2, 'i'),
    (default, 'Qual o planeta mais próximo do Sol?', 'Mercúrio', 'Terra', 'Júpiter', 'Netuno', 2, 'v'),
    (default, 'Em que país se anda mais de bicicleta?', 'Países Baixos', 'Portugal', 'Brasil', 'Mongólia', 2, 'v'),
    (default, 'Qual o metal cujo símbolo químico é o Au?', 'Ouro', 'Cobre', 'Mercúrio', 'Manganês', 2, 'v'),
    (default, 'Quem amamentou os gêmeos Rômulo e Remo?', 'uma loba', 'uma gata', 'uma vaca', 'uma ovelha', 2, 'i'),
    (default, 'Que animal gruguleja?', 'o peru', 'a cacatua', 'a garça', 'o pavão', 2, 'v'),
    (default, 'Quantos olhos a maior parte das aranhas têm?', 'Quatro pares', 'Quatro', 'Seis', 'Um', 2, 'i'),
    (default, 'Qual a maior floresta tropical do mundo?', 'Floresta Amazônica', 'Pantanal', 'Caatinga', 'Mata Atlântica', 2, 'v'),
    (default, 'Qual destes países é transcontinental?', 'Rússia', 'Filipinas', 'Istambul', 'Tanzânia', 2, 'i'),
    (default, 'O que a palavra legend significa em português?', 'Lenda', 'Legenda', 'Conto', 'História', 1, 'v'),
    (default, 'Qual o monumento famoso pela sua inclinação', 'Torre de Pisa', 'Cristo Redentor', 'Esfinge', 'Torre Eiffel', 1, 'v'),
    (default, 'Kryptonita é a fraqueza de qual super-herói?', 'Super-Homem', 'Capitão América', 'Flash', 'Hulk', 1, 'v'),
    (default, 'Qual a religião monoteísta que conta com o maior número de adeptos no mundo?', 'Cristianismo', 'Islamismo', 'Hinduísmo', 'Judaísmo', 1, 'v'),
    (default, 'Quais são os cromossomos que determinam o sexo masculino?', 'Os Y', 'Os W', 'Os X', 'Os V', 1, 'v'),
    (default, 'Quem pintou Mona Lisa?', 'Leonardo da Vinci', 'Salvador Dalí', 'Van Gogh', 'Pablo Picasso', 1, 'v'),
    (default, 'Qual a personagem mais famosa de Maurício de Sousa?', 'Mônica', 'Mafalda', 'Smurfette', 'Magali', 1, 'v'),
    (default, 'Qual o nome popular do cloreto de sódio?', 'Sal de cozinha', 'Fermento', 'Papel', 'Vinagre', 1, 'v'),
    (default, 'Que animal põe o maior ovo?', 'Avestruz', 'Galinha', 'Beija-flor', 'Pavão', 1, 'v'),
    (default, 'O que os pandas comem?', 'Bambu', 'Frutas e mel', 'Carnes', 'Mel', 1, 'v'),
    (default, 'Em que lugar vivem mais cangurus do que pessoas?', 'Austrália', 'Indonésia', 'Brasil', 'África do Sul', 1, 'v'),
    (default, 'Qual dessas aves não voa?', 'Pinguim', 'Pato', 'Cegonha', 'Galinha', 1, 'v'),
    (default, 'Depois do futebol, qual o esporte mais popular no Brasil?', 'Vôlei', 'Golfe', 'Esgrima', 'Esqui', 1, 'v'),
    (default, 'Em que país foi construído o Muro de Berlim?', 'Alemanha', 'Brasil', 'Uruguai', 'Polônia', 1, 'v'), 
    (default, 'A que temperatura a água ferve?', '100 ºC', '180 ºC', '0 ºC', '200 ºC', 1, 'v'),
    (default, 'Qual o maior planeta do sistema solar?', 'Júpiter', 'Terra', 'Saturno', 'Marte', 1, 'v'),
    (default, 'Qual a montanha mais alta do mundo?', 'Monte Everest', 'Mauna Kea', 'Pico da Neblina', 'Monte Chimborazo', 1, 'v'),
    (default, 'Onde se localiza Machu Picchu?', 'Peru', 'China', 'Bolívia', 'Índia', 1, 'v'),
    (default, 'Como se chamam os vasos que transportam sangue do coração para a periferia do corpo?', 'artérias', 'átrios', 'veias', 'aurículos', 1, 'v'),
    (default, 'Que país tem o formato de uma bota?', 'Itália', 'Brasil', 'Portugal', 'Butão', 1, 'v'),
    (default, 'Qual o maior animal terrestre?', 'Elefante africano', 'Tubarão Branco', 'Dinossauro', 'Girafa', 1, 'v'),
    (default, 'Qual a unidade que mede a intensidade do som?', 'Decibel', 'Frequência', 'Hertz', 'Compasso', 1, 'v'),
    (default, 'Qual era o deus romano do amor?', 'Cupido', 'Eros', 'Baco', 'Apolo', 1, 'v'),
    (default, 'Qual a montanha mais alta do Brasil?', 'Pico da Neblina', 'Pico Paraná', 'Monte Roraima', 'Pico da Bandeira', 1, 'v'),
    (default, 'Quem é o autor de “O Príncipe”?', 'Maquiavel', 'Montesquieu', 'Hobbes', 'Rousseau', 1, 'v');
    
    insert into denuncia_validacao values
	(default, 0, 0, NULL, NULL, 1),
    (default, 0, 0, NULL, NULL, 2),
    (default, 0, 0, NULL, NULL, 3),
    (default, 0, 0, NULL, NULL, 4),
    (default, 0, 0, NULL, NULL, 5),
    (default, 0, 0, NULL, NULL, 6),
    (default, 0, 0, NULL, NULL, 7),
    (default, 0, 0, NULL, NULL, 8),
    (default, 0, 0, NULL, NULL, 9),
    (default, 0, 0, NULL, NULL, 10),
    (default, 0, 0, NULL, NULL, 11),
    (default, 0, 0, NULL, NULL, 12),
    (default, 0, 0, NULL, NULL, 13),
    (default, 0, 0, NULL, NULL, 4),
    (default, 0, 0, NULL, NULL, 15),
    (default, 0, 0, NULL, NULL, 16),
    (default, 0, 0, NULL, NULL, 17),
    (default, 0, 0, NULL, NULL, 18),
    (default, 0, 0, NULL, NULL, 19),
    (default, 0, 0, NULL, NULL, 20),
    (default, 0, 0, NULL, NULL, 21),
    (default, 0, 0, NULL, NULL, 22),
    (default, 0, 0, NULL, NULL, 23),
    (default, 0, 0, NULL, NULL, 24),
    (default, 0, 0, NULL, NULL, 25),
    (default, 0, 0, NULL, NULL, 26),
    (default, 0, 0, NULL, NULL, 27),
    (default, 0, 0, NULL, NULL, 28),
    (default, 0, 0, NULL, NULL, 29),
    (default, 0, 0, NULL, NULL, 30),
    (default, 0, 0, NULL, NULL, 31),
    (default, 0, 0, NULL, NULL, 32),
    (default, 0, 0, NULL, NULL, 33),
    (default, 0, 0, NULL, NULL, 34),
    (default, 0, 0, NULL, NULL, 35),
    (default, 0, 0, NULL, NULL, 36),
    (default, 0, 0, NULL, NULL, 37),
    (default, 0, 0, NULL, NULL, 38),
    (default, 0, 0, NULL, NULL, 39),
    (default, 0, 0, NULL, NULL, 40),
    (default, 0, 0, NULL, NULL, 41),
    (default, 0, 0, NULL, NULL, 42),
    (default, 0, 0, NULL, NULL, 43),
    (default, 0, 0, NULL, NULL, 44),
    (default, 0, 0, NULL, NULL, 45),
    (default, 0, 0, NULL, NULL, 46),
    (default, 0, 0, NULL, NULL, 47),
    (default, 0, 0, NULL, NULL, 48),
    (default, 0, 0, NULL, NULL, 49),
    (default, 0, 0, NULL, NULL, 50),
    (default, 0, 0, NULL, NULL, 51),
    (default, 0, 0, NULL, NULL, 52),
    (default, 0, 0, NULL, NULL, 53),
    (default, 0, 0, NULL, NULL, 54),
    (default, 0, 0, NULL, NULL, 55),
    (default, 0, 0, NULL, NULL, 56),
    (default, 0, 0, NULL, NULL, 57),
    (default, 0, 0, NULL, NULL, 58),
    (default, 0, 0, NULL, NULL, 59),
    (default, 0, 0, NULL, NULL, 60),
    (default, 0, 0, NULL, NULL, 61),
    (default, 0, 0, NULL, NULL, 62),
    (default, 0, 0, NULL, NULL, 63),
    (default, 0, 0, NULL, NULL, 64),
    (default, 0, 0, NULL, NULL, 65),
    (default, 0, 0, NULL, NULL, 66),
    (default, 0, 0, NULL, NULL, 67),
    (default, 0, 0, NULL, NULL, 68),
    (default, 0, 0, NULL, NULL, 69),
    (default, 0, 0, NULL, NULL, 70),
    (default, 0, 0, NULL, NULL, 71),
    (default, 0, 0, NULL, NULL, 72),
    (default, 0, 0, NULL, NULL, 73),
    (default, 0, 0, NULL, NULL, 74),
    (default, 0, 0, NULL, NULL, 75),
    (default, 0, 0, NULL, NULL, 76),
    (default, 0, 0, NULL, NULL, 77),
    (default, 0, 0, NULL, NULL, 78),
    (default, 0, 0, NULL, NULL, 79),
    (default, 0, 0, NULL, NULL, 80);